/**
 * Chapter story types generated by TRACE Story Engine
 */

export interface LifeChapter {
  id: string;
  orderNumber: string; // e.g. "01", "02"
  title: string;
  timeRange: string;
  summary: string;
  evidence: string;
  dominantActivity: string;
  supportingMetrics: { label: string; value: string }[];
  keyMomentReceiptIds: string[];
  patterns: string[];
  connectedMomentsCount: number;
}
